### ISSUE TITLE
Use of undeclared type 'BinaryInteger' & 'SignedNumeric' in in xcode 8.3.1

### ISSUE THREAD

**Issue by varun-naharia** [mkrd/Swift-Big-Integer#12]
I am getting error in SMP.swift file 

![screen shot 2017-10-03 at 5 53 24 pm](https://user-images.githubusercontent.com/10987732/31124850-cd94757e-a863-11e7-86b4-ef424f93c379.png)

I just copied SMP.swift from master branch file in my project and tried to compile 

Please let me know what's wrong there

**Comment by mkrd** [comment]
Are you running it in a Swift 4 project? It won't work with Swift 3 or lower

**Comment by varun-naharia** [comment]
I am using it in swift 3

**Comment by mkrd** [comment]
For the library to work you will need swift 4. Unfortunately I can't provide backwards compatibility, if you really need it to work in swift 3 you could try to refactor it by yourself (although that will be hassle)
