### ISSUE TITLE
Cannot Build

### ISSUE THREAD

**Issue by doffing81** [mkrd/Swift-Big-Integer#15]
I simply threw this in a new project, but it will not build due to 1 issue:

> Command failed due to signal: Segmentation fault: 11

Xcode 8.3.3

**Comment by mkrd** [comment]
Have you tried it with xcode 9 and swift 4? The code will not work if you use swift 3.

**Comment by doffing81** [comment]
I have not, and may attempt to do so in the future.  I assumed it worked for Swift 3 as that is what it says in README.md, and in the SMP.swift file, it says version 2.0 is fully compatible with Swift 3.  I guess I am unsure what version the current SMP.swift file is on.

**Comment by mkrd** [comment]
I see. That should be a 4 in the SMP.swift file, I forgot to change that
