### ISSUE TITLE
Swift 3 support

### ISSUE THREAD

**Issue by pakLebah** [mkrd/Swift-Big-Integer#2]
Hi,

Since now Swift 2 is deprecated, when swift 3 support will come?

Thank you.

-Bee

**Comment by mkrd** [comment]
Hi, I already have a Swift 3 version, but I had to stop the project for a while because of a few final exams. I will upload the latest version as soon as possible!

**Comment by mkrd** [comment]
The Swift 3 version is online now ;)

**Comment by pakLebah** [comment]
Thank you! 😊
