### ISSUE TITLE
Formatter support

### ISSUE THREAD

**Issue by pakLebah** [mkrd/Swift-Big-Integer#3]
Hi,

Do you have any plan to give it a number formatter support? I need at least a thousand separator, a decimal separator, and currency symbol, similar to NumberFormatter.

Thank you.

Regards,

-Bee

**Comment by mkrd** [comment]
I have no plans yet, but I think it would be a good idea to implement this as a finance extension. I will take a look at this after work!

**Comment by pakLebah** [comment]
It would be great if the NumberFormatter class is able to accept Big Integer/Double. 😊

**Comment by mkrd** [comment]
I will pick up this suggestion some time, but for now I don't have the time to implement it. Sorry :(

**Comment by davdroman-rdx** [comment]
@mkrd have plans changed at all on this since? We want to incorporate this library onto our codebase but we're really dependant on proper formatter support in order to do so.
