### ISSUE TITLE
BDouble.DecimalExpansion produces incorrect results for some BDouble values unless precision is set higher

### ISSUE THREAD

**Issue by Ben-Henshall** [mkrd/Swift-Big-Integer#32]
It appears that for some values of BDouble, decimal expansion produces incorrect values below certain precision points.

For example, I added the following test case to the project:
<img width="809" alt="screen shot 2018-04-25 at 18 12 44" src="https://user-images.githubusercontent.com/15949658/39261441-5fd38d9e-48b4-11e8-908e-f13f1731d270.png">
`bigD?.decimalExpansion(precisionAfterComma: 2)` is expected to equal `"0.71"`, but instead resolves to "0.00".   
 
This is also the case for any precision value up to 9, where the decimalExpansions resolves to what it is expected to be:
<img width="394" alt="screen shot 2018-04-25 at 18 15 23" src="https://user-images.githubusercontent.com/15949658/39261554-be8a5458-48b4-11e8-8b89-08ef802bdaa6.png">

I don't know enough about the maths side of this to fix it, but I had a quick look at the `decimalExpansion` function and found this block of code:
```
if res.count < digits + 2
{
  let pad = String(repeating: "0", count: max(digits, 1))
  res = res.padding(toLength: digits+2-origRes.count, withPad: pad, startingAt: res.count)
}
```

Removing that `res.count < digits + 2` check fixes this issue, but I'm guessing it's required for some other reason?
All the tests in the project pass if this block is removed.

**Comment by mkrd** [comment]
Hi! I fixed the issue, it should return the proper decimal expansion now. I also added a test that generates random "decimal expansions", converts them to DBouble, and den extracts the original value with the decimalExpansion function. I would appreciate some more tests, since I'm not 100% sure that my test covers every case

**Comment by twodayslate** [comment]
I apologize for these errors as they are most likely mine. I am glad to see that other people are using this library. More tests are always appreciated. 

Personally I'd rather 0.716x with a precision of 2 be 0.72

I have no preference on a BDouble with a precision of 0 but would be easy enough to code with `ceil`

**Comment by mkrd** [comment]
@Ben-Henshall Thanks for pointing that out. I already added a test that checks these cases: `func testDecimalExpansion()
	{
		let testValues = [
			("0", "0.0", 0),
			("0", "0.0", 1),
			("0", "0.00", 2),
			("0", "0.000", 3),
			("12.345", "12.0", 0),
			("12.345", "12.3", 1),
			("12.345", "12.34", 2),
			("12.345", "12.345", 3),
			("12.345", "12.3450", 4),
			("-0.00009", "0.0000", 4),
			("-0.00009", "-0.00009", 5),
			("-0.00009", "-0.000090", 6),
		]

		for (original, test, precision) in testValues
		{
			let result = BDouble(original)!.decimalExpansion(precisionAfterDecimalPoint: precision)
			XCTAssert(result == test)
		}
	}`
But it would be nice if you'd take a look at them, maybe you can find some more cases that were not covered previously.

I also figured that the decimal expansion should always contain a decimal point, so the decimal expansion of "42" with precision 0 would be "42.0"

@twodayslate How about a second function like "decimalExpansionWithRounding"?

**Comment by Ben-Henshall** [comment]
The test cases provided in there all passed with the previous code, so we should add tests to test for the issue that we've fixed. These can be added to the list of test cases you have there @mkrd :

```
      ("-0.7162", "-0.7", 1),
      ("-0.7162", "-0.71", 2),
      ("-0.7162", "-0.716", 3),
      ("-0.7162", "-0.7162", 4),
      ("-0.7162", "-0.7162000000", 10),
```

It's super minor, but I'd also suggest changing the `XCTAssert(result == test)` to `XCTAssertEqual(result, test)` instead as the latter gives detailed information on each test that fails and shows the comparison rather than a generic "This test failed" message.

**Comment by Ben-Henshall** [comment]
As for decimal expansion with a precision of 0 being "x.0" rather than "x", you're absolutely right. That makes much more sense than my suggestion.
