### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by pakLebah** [mkrd/Swift-Big-Integer#4]
Hi,

I just tried this library on Linux but it failed. I tried to fix it but then I gave up because the errors are out of my knowledge level yet. I tested it on Linux Ubuntu 14.04 using Swift v3.

So, any plan to support Linux? I need this library to support my web app (written in Swift).

Thank you.

-Bee

**Comment by mkrd** [comment]
That's very strange. I have no access to a linux computer, so I can't find the error... I wrote all code in xcode for swift 3 and it works without any problems. Maybe swift for linux is not fully compatible with native swift?

**Comment by pakLebah** [comment]
It's not strange. It's well-known that Swift's RTL/SDK isn't yet fully available on Linux. Sometimes you need to call Linux's Glibc to cover some things that are not available or not supported by Foundation module e.g. random function.

You may use on-the-cloud Linux VM providers to experiment with Swift on Linux. I have been using free [CodeAnywhere](http://codeanywhere.com) service to study Swift on Linux, especially for web programming. Use CodeAnywhere's Ubuntu C/C++ dev container and install Swift v3 manually on it. Try it out! :)

**Comment by mkrd** [comment]
Well thats a problem of apple then. They should make sure that all correct code runs the same on every platform
